Automatic formatting with clang-format and black
InsightSoftwareConsortium/ITKSoftwareGuide pull request #177
Opened 2022-03-01 16:10 UTC by Leengit

2022-03-01 18:33 UTC, hjmjohnson approved these changes

2022-03-01 18:36 UTC, hjmjohnson requested changes
Can the .clang-format file from ITK be included in this repo to ensure that the style is the same as ITK proper?

2022-03-01 18:40 UTC, dzenanz submitted a review, later dismissed

2022-03-01 18:41 UTC, Leengit commented
> Can the .clang-format file from ITK be included in this repo to ensure that the style is the same as ITK proper?

Done and force-pushed.

2022-03-01 20:20 UTC, Leengit commented on SoftwareGuide/Examples/ParseCxxExamples.py
> +                            "{filename}:{line}: warning: Line after start of LaTeX block should be a newline -- instead got {value}".format(
I submitted #178.

2022-03-02 02:30 UTC, hjmjohnson approved these changes

2022-03-02 02:31 UTC, merged